"""My platform constants"""

DOMAIN = "coway"

IOCARE_FAN_OFF = "0"
IOCARE_FAN_LOW = "1"
IOCARE_FAN_MEDIUM = "2"
IOCARE_FAN_HIGH = "3"

IOCARE_TIMER_OFF = "0"
IOCARE_TIMER_1H = "60"
IOCARE_TIMER_2H = "120"
IOCARE_TIMER_4H = "240"
IOCARE_TIMER_8H = "480"
